# Generated by Django 4.2.7 on 2025-12-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_core", "0001_initial"),
    ]

    operations = []
